### ISSUE TITLE
[SUCCESS] - RT-AX86U

### ISSUE THREAD

**Issue by dorner365** [ExtremeFiretop/MerlinAutoUpdate-Router#146]
The script properly initiated the backup, emailed about the F/W upgrade start and then successful update.

MerlinAU v.1.05

RT-AX86U
Starting Firmware Version: 3004.388.6
Updated Firmware Version: 3004.388.6_2

Thank you!

**Comment by ExtremeFiretop** [comment]
Thank you! Our documentation will be updated to reflect this :)
