### ISSUE TITLE
Cron job 'MerlinAU' already exists[REQ] - 

### ISSUE THREAD

**Issue by dorner365** [ExtremeFiretop/MerlinAutoUpdate-Router#148]
Not a feature request nor an issue per se. Just a question...

When starting the script, if the cron job already exists, why not move on to the menu without additional text or key entry?

**Comment by ExtremeFiretop** [comment]
Thank you for your suggestion!

Me and Martinski will discuss the pros and cons of this and report back

**Comment by ExtremeFiretop** [comment]
@dorner365 

Martinski and I discussed the pros and cons, the added value is that when we run the script interactively it informs that:

1) The cron job currently exists in crontab.
2) The cron job hook is currently placed in the 'services-start' F/W script.

That is useful status information for newer users that care about being informed about the changes being done to their router.

We just need to press the Enter key to continue. Easy -  It doesn't hinder, obstruct, or interfere with normal functionality. 
In fact, given the recently reported problems with missing cron jobs, we welcome those status messages that let us know that the cron job still exists, and is alive & well. 

Also, once the script has been set up like you want, people won't normally run it interactively often, and on the occasions that they do, those informational messages are useful for the reasons given above.

For now, this will be closed. Thank you for the suggestion and feedback all the same! :)
