### ISSUE TITLE
[BUG] - "Required USB storage device is not connected or not mounted correctly" despite MerlinAU dirs being created

### ISSUE THREAD

**Issue by DanielJonesEB** [ExtremeFiretop/MerlinAutoUpdate-Router#161]
It's entirely possible this is PEBKAC, as I don't really know what I'm doing 😁 

**Describe the bug**

I've got BACKUPMON installed and configured, and have done a successful backup. I try running a firmware update, and I get the following:

```
Running the update task now... Checking for F/W updates...
Expected directory path /tmp/mnt/Samsung_T1/Archives is NOT found.
**ERROR**: Required USB storage device is not connected or not mounted correctly.

Press Enter to return to the Main Menu...
```

However, this directory definitely exists and the `MerlinAU.d` directory was even created:

```
admin@GT-AX11000-6E00:/tmp/mnt/Samsung_T1/Archives/MerlinAU.d# find .
.
./GT-AX11000_firmware
./logs
./logs/GT-AX11000_FW_Update_2024-03-14_19_47_42.log
./logs/GT-AX11000_FW_Update_2024-03-14_19_48_59.log
```

I've got that Samsung SSD mounted, and it serves some Samba shares, as well as being the target for BACKUPMON backups:

```
# df -h
Filesystem                Size      Used Available Use% Mounted on
ubi:rootfs_ubifs         69.4M     68.0M      1.5M  98% /
devtmpfs                441.1M         0    441.1M   0% /dev
tmpfs                   441.2M      1.3M    439.9M   0% /var
tmpfs                   441.2M      2.3M    438.9M   1% /tmp/mnt
mtd:bootfs                5.1M      4.2M    968.0K  82% /bootfs
mtd:data                  8.0M      6.4M      1.6M  80% /data
tmpfs                   441.2M      2.3M    438.9M   1% /tmp/mnt
tmpfs                   441.2M      2.3M    438.9M   1% /tmp
/dev/mtdblock9           63.0M      9.4M     53.6M  15% /jffs
/dev/sda1               931.5G    784.3G    147.2G  84% /tmp/mnt/Samsung_T1
/dev/sdc1                28.1G      2.1G     24.6G   8% /tmp/mnt/diversion
/dev/sdb                  1.8T    535.1G      1.3T  29% /tmp/mnt/Samsung_T5
tmpfs                   441.2M      2.3M    438.9M   1% /www/require/modules/menuTree.js
```

Here's the banner that MerlinAU displays. Note that it says the USB drive is connected:

```
    __  __           _ _               _    _
   |  \/  |         | (_)         /\  | |  | |
   | \  / | ___ _ __| |_ _ __    /  \ | |  | |
   | |\/| |/ _ | '__| | | '_ \  / /\ \| |  | |
   | |  | |  __| |  | | | | | |/ ____ | |__| |
   |_|  |_|\___|_|  |_|_|_| |_/_/    \_\____/ v1.0.7

========= By ExtremeFiretop & Martinski W. ==========

-----------------------------------------------------
      F/W Product/Model ID:  GT-AX11000
      F/W Update Available:  3004.388.6.2 <<---
      F/W Version Installed: 3004.388.4.0_rog
      USB Storage Connected: True
-----------------------------------------------------
```

**Expected behavior**
Firmware should be downloaded and installed

**Router Information (please complete the following information):**
 - Router Model [e.g. RT-AX88U]: GT-AX11000
 - Firmware Version: [e.g. 3004.388.5]: 3004.388.4.0_rog
 - Other Scripts?: Diversion, Skynet, BACKUPMON

**Comment by DanielJonesEB** [comment]
_sigh_

Rebooted the router, tried again and it got further. Apologies for the false alarm!

**Comment by ExtremeFiretop** [comment]
> _sigh_
> 
> Rebooted the router, tried again and it worked. Apologies for the false alarm!
> 
> Thanks very much for this script. Upgrading previously was both scary and a hassle, so I really appreciate this.

It's possible the USB wasn't mounted correctly and rebooting cleared out the invalid mount point. This was a safety we put into play to stop the updates if the expected mount located and the actual mount locations don't match. 

Did you happen to confirm the USB looked mounted correctly in the WebUI before rebooting? For example it should of been seen by the router as being called: Samsung_T1 and not Samsung_T1(1)

Also was the download location in MerlinAU still /tmp/mnt/Samsung_T1/Archives post-reboot and it worked? Did you happen to unplug, unmount or change the storage device *after* setting up MerlinAU?

This example above could potentially cause a mismatch or an issue where the router remounts the USB under a different name/label if the existing label is "in use" for some reason. Again you would expect this to be cleared out once rebooted.

**Comment by ExtremeFiretop** [comment]
Either way I'm happy to hear it worked as expected once you got over the little hick-up. 

Do let us know if you notice it again and we may ask you to pull out some logs.

I already want to adjust that messaging to be more clear. It tells us the expected value but doesn't give us the current values, etc. I'm sure there's areas we could improve.

**Comment by Martinski4GitHub** [comment]
> 
> I already want to adjust that messaging to be more clear. It tells us the expected value but doesn't give us the current values,...
>
You're right. The code should report the found mount points as well. See PR #162 to address this.

**Comment by ExtremeFiretop** [comment]
Hello @DanielJonesEB 

Would you be available to test something for us if you still have this router with the ROG WebUi installed?

Let me know!
Joel S.
