### ISSUE TITLE
Login failed for non-existent AiMesh Node - [BUG] - 

### ISSUE THREAD

**Issue by dorner365** [ExtremeFiretop/MerlinAutoUpdate-Router#253]
Router model: RT-AX68U
F/W: 388.7_0
Scripts: skynet, unbound (w/dnsmasq disabled), sc merlin, backupmon

Starting with v.1.24 the following error shows when manually checking for new firmware:

"Enter selection:  1

MerlinAU v1.2.4
Running the update task now... Checking for F/W updates...

Login failed for AiMesh Node [192.168.2.3].
No new firmware version update is found for [RT-AX86U] router model.

Press <Enter> to return to the Main Menu...
"
NOTE: There is no AiMesh Node and the router 192.168.2.3 is offline.

Probably a couple of years ago I experimented with AiMesh for a short period of time and then 192.168.2.3 became a Media Bridge. However, as I said, the actual 192.168.2.3 is not even online nowadays.

So, probably some irrelevant nvram leftovers on the main router (RT-AX86U)...

**Comment by ExtremeFiretop** [comment]
> Router model: RT-AX68U F/W: 388.7_0 Scripts: skynet, unbound (w/dnsmasq disabled), sc merlin, backupmon
> 
> Starting with v.1.24 the following error shows when manually checking for new firmware:
> 
> "Enter selection: 1
> 
> MerlinAU v1.2.4 Running the update task now... Checking for F/W updates...
> 
> Login failed for AiMesh Node [192.168.2.3]. No new firmware version update is found for [RT-AX86U] router model.
> 
> Press to return to the Main Menu... " NOTE: There is no AiMesh Node and the router 192.168.2.3 is offline.
> 
> Probably a couple of years ago I experimented with AiMesh for a short period of time and then 192.168.2.3 became a Media Bridge. However, as I said, the actual 192.168.2.3 is not even online nowadays.
> 
> So, probably some irrelevant nvram leftovers on the main router (RT-AX86U)...

Can you run both:

`nvram get asus_device_list`

And

`nvram get cfg_device_list`

And provide the output?

**Comment by dorner365** [comment]
First:
@RT-AX86U_D:/tmp/mnt/asus/conf# nvram get asus_device_list
<3>RT-AC66U_B1>192.168.2.3>48:F8:B3:A7:9B:08>0>xfinitywifi>255.255.255.0>4
...that's the manually assigned IP in the DHCP server
Second:
empty output.

**Comment by ExtremeFiretop** [comment]
> First: @RT-AX86U_D:/tmp/mnt/asus/conf# nvram get asus_device_list <3>RT-AC66U_B1>192.168.2.3>48:F8:B3:A7:9B:08>0>xfinitywifi>255.255.255.0>4 ...that's the manually assigned IP in the DHCP server Second: empty output.

Is this stopping you from running a regular update on your actual primary router?

**Comment by dorner365** [comment]
I couldn't answer that since currently there is no update.

**Comment by ExtremeFiretop** [comment]
> I couldn't answer that since currently there is no update.

Fair, I just figured you may have had a successful update over MerlinAU to v388.7_0 in the past. Since you say this Aimesh node was added some 2 years ago.

> First: @RT-AX86U_D:/tmp/mnt/asus/conf# nvram get asus_device_list <3>RT-AC66U_B1>192.168.2.3>48:F8:B3:A7:9B:08>0>xfinitywifi>255.255.255.0>4 ...that's the manually assigned IP in the DHCP server Second: empty output.

Have you tried removing that nvram value? 
Static dhcp assignments are held in the **dhcp_staticlist** value, can be checked with: 
```
nvram get dhcp_staticlist 
```
and
```
 nvram get dhcp_hostnames
```
(Unless you have an addon like YazDHCP)

It should usually be removed by the router once the AiMesh node is unpaired through the WebUI.
Unless you maybe restored the router to a previous backup that had the AiMesh node at some point?

**Comment by ExtremeFiretop** [comment]
I see an area of improvement for the code around AiMesh nodes.
I do believe this would stop your primary router from updating.

**Comment by ExtremeFiretop** [comment]
@dorner365 

Created commit: https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/commit/c94d0a398dedceec1697930517a92857b3df537d

For this in dev. Let me know if your available to test this version. (As long as you haven't removed the nvram variable yet)

**Comment by ExtremeFiretop** [comment]
Can be downloaded and tested with:

`curl --retry 3 "https://raw.githubusercontent.com/ExtremeFiretop/MerlinAutoUpdate-Router/dev/MerlinAU.sh" -o "/jffs/scripts/MerlinAU.sh" && chmod 755 "/jffs/scripts/MerlinAU.sh"`

**Comment by dorner365** [comment]
I have no plans to remove that value since I use that device at times.
Yes, I'll try it and get back to you soon.

**Comment by ExtremeFiretop** [comment]
> I have no plans to remove that value since I use that device at times. Yes, I'll try it and get back to you soon.

So it's just offline for now? But you do still own the device?
In that case yes, don't remove it. 

Test the dev version and report back when you can :)

**Comment by dorner365** [comment]
> So it's just offline for now? But you do still own the device?
> In that case yes, don't remove it.

Correct.

Here's the output of the dev version:

"Enter selection:  1

MerlinAU v1.2.4
Running the update task now... Checking for F/W updates...
No new firmware version update is found for [RT-AX86U] router model.

Press <Enter> to return to the Main Menu...
".
That fixed it - thank you!

**Comment by ExtremeFiretop** [comment]
@dorner365 

Fantastic news. I'll close this issue , I'm currently going to be working on other updates today, but you can expect this change to be apart of the next release.

@Martinski4GitHub 

Please review commit: https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/commit/c94d0a398dedceec1697930517a92857b3df537d

I merged it straight into dev for testing of the issue. 

Thanks for reporting!
