### ISSUE TITLE
[REQ] - That it actually performs an autoupdate at a specific time.

### ISSUE THREAD

**Issue by simonbcn** [ExtremeFiretop/MerlinAutoUpdate-Router#279]
Although the script is called "_MerlinAutoUpdate-Router_", it does not actually perform an automatic update. It only notifies you that there is a new update. To perform an update, human intervention is required, which means that the term "_auto_" is not really accurate.
This script would be more useful if it allowed specifying a time for the actual automatic firmware update. In this way, the process would be truly automatic and more convenient. The firmware update interrupts the Internet connection, and when I read the notice that there is an update, it is usually when I need Internet access, so I have to set an additional reminder to execute the firmware update at another time. The email notification would be in this case after the firmware update.

**Comment by ExtremeFiretop** [comment]
> Although the script is called "_MerlinAutoUpdate-Router_", it does not actually perform an automatic update. It only notifies you that there is a new update. To perform an update, human intervention is required, which means that the term "_auto_" is not really accurate. This script would be more useful if it allowed specifying a time for the actual automatic firmware update. In this way, the process would be truly automatic and more convenient. The firmware update interrupts the Internet connection, and when I read the notice that there is an update, it is usually when I need Internet access, so I have to set an additional reminder to execute the firmware update at another time. The email notification would be in this case after the firmware update.


This is exactly what the script does.
Please read the FAQ and the forums if you have any questions.

Thanks.

**Comment by Martinski4GitHub** [comment]
> Although the script is called "_MerlinAutoUpdate-Router_", it does not actually perform an automatic update. It only notifies you that there is a new update. To perform an update, human intervention is required, which means that the term "_auto_" is not really accurate. 
>
>
You clearly have not looked closely & carefully enough at the MerlinAU UI menus and the 2 options to set up a CRON schedule & to set the postponement period for F/W updates. If you had taken the time to carefully look, you would know what "auto" actually means. If you don't know how to set up the CRON schedule or don't know what that means, perhaps the MerlinAU is not the right script for you.
