### ISSUE TITLE
[Help] Connection problem to web interface

### ISSUE THREAD

**Issue by SolidRhino** [ExtremeFiretop/MerlinAutoUpdate-Router#290]
When I set my password and test the connection to the web interface, I get the following error:

![CleanShot 2024-08-14 at 20 31 16@2x](https://github.com/user-attachments/assets/5bff64d4-11ef-40d0-a9d6-50a2f6a92292)

The password is correct so I don't know what the error is.

**Comment by ExtremeFiretop** [comment]
> When I set my password and test the connection to the web interface, I get the following error:
> 
> ![CleanShot 2024-08-14 at 20 31 16@2x](https://private-user-images.githubusercontent.com/222683/357957402-5bff64d4-11ef-40d0-a9d6-50a2f6a92292.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NjEzMzcsIm5iZiI6MTcyMzY2MTAzNywicGF0aCI6Ii8yMjI2ODMvMzU3OTU3NDAyLTViZmY2NGQ0LTExZWYtNDBkMC1hOWQ2LTUwYTJmNmE5MjI5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNFQxODQzNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MzQ2ODBlN2IxYjgwOTQ2MWI3YzUyMzU3NGU1M2U3MzE5Yjg1OWM4NmQ2NTMxMzYwMjBlNjcxOGNlOTRiMjQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WTMJ_tsq7CYUWonbaSxyr0Rudo-3UuJ66BmsHeIWiNY)
> 
> The password is correct so I don't know what the error is.

The error says it's unable to login to your local router "RT-AX86U_PRO-E9F0.lan on port 80.
Do you have port 80 blocked for local login?

**Comment by ExtremeFiretop** [comment]
> When I set my password and test the connection to the web interface, I get the following error:
> 
> ![CleanShot 2024-08-14 at 20 31 16@2x](https://private-user-images.githubusercontent.com/222683/357957402-5bff64d4-11ef-40d0-a9d6-50a2f6a92292.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NjI3NjMsIm5iZiI6MTcyMzY2MjQ2MywicGF0aCI6Ii8yMjI2ODMvMzU3OTU3NDAyLTViZmY2NGQ0LTExZWYtNDBkMC1hOWQ2LTUwYTJmNmE5MjI5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNFQxOTA3NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MWViNmJmZjM4MzZiM2UyMTYwMGM3OWFmNTdlNDAzNWQyNDg3ZDU5NDgyZDBmNGZjYmI3ZDkzMDBjZmE1YmFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.S1W7Giip8YupexGdkwjWHGHscq5XkfIv8M63N1_pUhI)
> 
> The password is correct so I don't know what the error is.

For diagnostics purposes, can I ask you to send the results of the following commands (including enclosing curly bracket):

```
{
_shownvram_() { printf "$1=[%s]\n" "$(nvram get "$1")" ; }
_shownvram_ http_enable
_shownvram_ lan_domain
_shownvram_ lan_hostname
_shownvram_ http_lanport
_shownvram_ https_lanport
}
```

**Comment by ExtremeFiretop** [comment]
Don't forget you can hit the "Tab" key to view the password as you type it.

Also, make sure nothing else is logged into the WebUI while testing.

**Comment by SolidRhino** [comment]
The password is correct and nothing else is logged in. When I run your command for dignostic I get the following response:
```

http_enable=[2]
lan_domain=[lan]
lan_hostname=[RT-AX86U_Pro-E9F0]
http_lanport=[80]
https_lanport=[8443]
```

**Comment by ExtremeFiretop** [comment]
> The password is correct and nothing else is logged in. When I run your command for dignostic I get the following response:
> 
> ```
> 
> http_enable=[2]
> lan_domain=[lan]
> lan_hostname=[RT-AX86U_Pro-E9F0]
> http_lanport=[80]
> https_lanport=[8443]
> ```

Sorry just to be completely clear, you had already mentioned in your first post the password is correct.
Can you confirm that you viewed the password with the TAB key?

Do you have "Enable Access Restrictions" on?

![image](https://github.com/user-attachments/assets/ff89e272-4335-4e48-8171-5fa535f3468e)

What authentication method is the router set too:

![image](https://github.com/user-attachments/assets/40b9e1d0-ac1e-4a1c-8d69-cc1425eac010)

Can you test accessing the routers web UI with the URL below:

http://RT-AX86U_Pro-E9F0.lan

**Comment by ExtremeFiretop** [comment]
> When I set my password and test the connection to the web interface, I get the following error:
> 
> ![CleanShot 2024-08-14 at 20 31 16@2x](https://private-user-images.githubusercontent.com/222683/357957402-5bff64d4-11ef-40d0-a9d6-50a2f6a92292.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NzEzNTgsIm5iZiI6MTcyMzY3MTA1OCwicGF0aCI6Ii8yMjI2ODMvMzU3OTU3NDAyLTViZmY2NGQ0LTExZWYtNDBkMC1hOWQ2LTUwYTJmNmE5MjI5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNFQyMTMwNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZDljYTQzMjllN2NkOWQ0OWE3ZjlmMjg2YTk0OGViNTJhZGIxYmEyYzg2YmMzMmQ5YzkzOTdjMjU1NTQ0NTkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DDKY3bMaGVKVtiz8IpmDgL50Ng4-Y5ctO5Aaf_BowGI)
> 
> The password is correct so I don't know what the error is.

@SolidRhino 
This is what I get when I try with an invalid made up password:

![image](https://github.com/user-attachments/assets/eadd754d-91ba-4110-b8e7-310078ca4d1a)

It does not say it can't connect on port 80, it just says login failed, In your case it's telling me the router is actively refusing the connection on that URL I mentioned: http://RT-AX86U_Pro-E9F0.lan

**Comment by SolidRhino** [comment]
> Do you have "Enable Access Restrictions" on?
> 
> ![image](https://private-user-images.githubusercontent.com/1971404/357979804-ff89e272-4335-4e48-8171-5fa535f3468e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MDQyMTMsIm5iZiI6MTcyMzcwMzkxMywicGF0aCI6Ii8xOTcxNDA0LzM1Nzk3OTgwNC1mZjg5ZTI3Mi00MzM1LTRlNDgtODE3MS01ZmE1MzVmMzQ2OGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTVUMDYzODMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGE0NGJiNzJhNjE4NzVlOTIzMzQzZjc4OWVkNTEwYjg0ZDU3YzA1YWE3N2MyYjRlZTBiMzU1NzIwYjE1M2E2YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.MyiR0hlnf1YA3-vR8l5eejATEhxNgt4Fxv4h8uEUkh0)
>

Thank you so much for pointing this out! This option had to be changed.

**Comment by ExtremeFiretop** [comment]
> > Do you have "Enable Access Restrictions" on?
> > ![image](https://private-user-images.githubusercontent.com/1971404/357979804-ff89e272-4335-4e48-8171-5fa535f3468e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MDQyMTMsIm5iZiI6MTcyMzcwMzkxMywicGF0aCI6Ii8xOTcxNDA0LzM1Nzk3OTgwNC1mZjg5ZTI3Mi00MzM1LTRlNDgtODE3MS01ZmE1MzVmMzQ2OGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTVUMDYzODMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGE0NGJiNzJhNjE4NzVlOTIzMzQzZjc4OWVkNTEwYjg0ZDU3YzA1YWE3N2MyYjRlZTBiMzU1NzIwYjE1M2E2YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.MyiR0hlnf1YA3-vR8l5eejATEhxNgt4Fxv4h8uEUkh0)
> 
> Thank you so much for pointing this out! This option had to be changed.

Happy to help, I figured something had to be blocking port 80, it was just a matter of finding what.
Enjoy automated updates!

**Comment by ExtremeFiretop** [comment]
@Martinski4GitHub 

We can detect the use of the access restrictions using this NVRAM value:

`enable_acc_restriction=0 (disabled)`

or
 
`enable_acc_restriction=1 (enabled)`

**Comment by SolidRhino** [comment]
I have added the router to the allowed list. Then it works.

**Comment by ExtremeFiretop** [comment]
> I have added the router to the allowed list. Then it works.

I am considering blocking entering a password if access restrictions is on with WebUI access restricted. If it's SSH restrictions only, then it don't block.

However, this this design you wouldn't be able to have access restrictions on for the WebUI and it would need to be limited to SSH only.

Would you prefer instructions detailing how to add the routers IP? Or just asking the user to disable WebUI access restrictions to continue?

Is there a reason you require the web access restrictions? Maybe this will help me understand why you would opt to add the routers IP address instead of disabling.

**Comment by SolidRhino** [comment]
I want to enable web access restrictions so that only I can connect to the router ssh and webinterface on the lan. So I think informatie is better than complete blocking the setup.

Isn't it possible to use localhost to communicate with the webui?

**Comment by ExtremeFiretop** [comment]
> Isn't it possible to use localhost to communicate with the webui?

I'm not sure I'm following, can you clarify this question?

As for the solution, me and Martinski have come to an agreed upon method to detect and advise of this setup.

The PR is currently open and pending approval.

Thanks!

**Comment by ExtremeFiretop** [comment]
> I want to enable web access restrictions so that only I can connect to the router ssh and webinterface on the lan. So I think informatie is better than complete blocking the setup.
> 
> Isn't it possible to use localhost to communicate with the webui?

Can you confirm that: `nvram get lan_ipaddr`

Is the IP you added to the rule? you don't need to share the IP, just confirm or deny that returns the IP you added. Thanks!
