### ISSUE TITLE
How do you update the script?

### ISSUE THREAD

**Issue by p1r473** [ExtremeFiretop/MerlinAutoUpdate-Router#332]
Hi, I cant seem to find any way to update the MerlinAU script
Can you add an option to update script please?
I checked under Advanced too and cant find anything.
![image](https://github.com/user-attachments/assets/51298569-c7b3-4734-9029-7e1d6897cf2a)

**Comment by ExtremeFiretop** [comment]
@p1r473 

Read the main menu.
