### ISSUE TITLE
[BUG] - "flash has been CANCELLED due to a failed backup" but it wasn't cancelled

### ISSUE THREAD

**Issue by dorner365** [ExtremeFiretop/MerlinAutoUpdate-Router#363]
Actually a better title would be: Successful Update! but oddity encountered.
2 RT-AX86U (one local and the other one remote over OVPN) from 3004.388.8_2 to 3004.388.8_4. Both completed successfully - thank you for a well written script! 

On the remote one BACKUPMON stopped working a couple of days ago. Please take a look at the output:
`Enter selection:  1

MerlinAU v1.3.6
Running the update task now... Checking for F/W updates...
Using release information for Merlin Firmware.
Required RAM: 111115 KB - RAM Free: 104452 KB - RAM Available: 180521 KB

Backup Started (by BACKUPMON)
mount: mounting \\192.168.1.250\nas on /tmp/mnt/astor failed: No route to host
mount: mounting \\192.168.1.250\nas on /tmp/mnt/astor failed: No route to host
mount: mounting \\192.168.1.250\nas on /tmp/mnt/astor failed: No route to host
Backup Finished

Backup Failed

Sending email notification [NEW_BM_BACKUP_FAILED].
Please wait...
The email notification was sent successfully [NEW_BM_BACKUP_FAILED].

**IMPORTANT NOTICE**:
The firmware flash has been CANCELLED due to a failed backup from BACKUPMON.
Please fix the BACKUPMON configuration, or consider uninstalling it to proceed flash.
Resolving the BACKUPMON configuration is HIGHLY recommended for safety of the upgrade.

Press <Enter> to return to the Main Menu...
Latest release version is 3004.388.8.4.
Downloading https://sourceforge.net/projects/asuswrt-merlin/files/RT-AX86U/Release/RT-AX86U_3004_388.8_4.zip
.
.
.
Required RAM: 111115 KB - RAM Free: 74968 KB - RAM Available: 178956 KB
-----------------------------------------------------------
Archive:  /tmp/mnt/asus/MerlinAU.d/RT-AX86U_firmware/RT-AX86U_firmware.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
 84410388  11-17-2024 15:06   RT-AX86U_3004_388.8_4_pureubi.w
     9717  11-17-2024 15:25   README-merlin.txt
   105327  11-17-2024 15:06   Changelog-NG.txt
       98  11-17-2024 15:06   sha256sum.sha256
 --------                     -------
 84525530                     4 files
-----------------------------------------------------------
Archive:  /tmp/mnt/asus/MerlinAU.d/RT-AX86U_firmware/RT-AX86U_firmware.zip
  inflating: RT-AX86U_3004_388.8_4_pureubi.w
  inflating: Changelog-NG.txt
  inflating: sha256sum.sha256
-----------------------------------------------------------
Required RAM: 111115 KB - RAM Free: 31056 KB - RAM Available: 157530 KB
Current version NOT found in changelog file. Bypassing changelog verification for this run.
Required RAM: 111115 KB - RAM Free: 31184 KB - RAM Available: 157870 KB
No ROG Build detected. Skipping.
SHA256 signature check for firmware image file passed successfully.
Required RAM: 111115 KB - RAM Free: 30432 KB - RAM Available: 157413 KB
Router Web URL is: http://RT-AX86U-M.??????
**IMPORTANT**:
The firmware flash is about to start.
Press <Enter> to stop now, or type Y to continue.
Once started, the flashing process CANNOT be interrupted.
Continue? [yY|nN]? y

OK

Restarting web server... Please wait.

Sending email notification [START_FW_UPDATE_STATUS].
Please wait...
The email notification was sent successfully [START_FW_UPDATE_STATUS].
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   228    0    84  100   144   1834   3145 --:--:-- --:--:-- --:--:--  5066
Searching for Entware services to stop...
Stopping Entware services...
Please wait.
-----------------------------------------------------------
/opt/etc/init.d/S61unbound
/opt/etc/init.d/S15upsd
/opt/etc/init.d/S15upsmon
/opt/etc/init.d/S80lighttpd
/opt/etc/init.d/S06tailscaled
-----------------------------------------------------------
 Checking lighttpd...              alive.
 Shutting down lighttpd...              done.
 Checking unbound...              alive.
 Shutting down unbound...              done.
 Checking upsmon...              alive.
 Shutting down upsmon...              done.
 Checking upsd...              alive.
 Shutting down upsd...              done.
 Checking tailscaled...              alive.
 Shutting down tailscaled...`

...and that's all the output I've had. However, the firmware upgrade, emails all worked. However, based on the warning above the script should have returned to the main menu based on the failed backup.

**Comment by ExtremeFiretop** [comment]
> Actually a better title would be: Successful Update! but oddity encountered. 2 RT-AX86U (one local and the other one remote over OVPN) from 3004.388.8_2 to 3004.388.8_4. Both completed successfully - thank you for a well written script!
> 
> On the remote one BACKUPMON stopped working a couple of days ago. Please take a look at the output: `Enter selection: 1
> 
> MerlinAU v1.3.6 Running the update task now... Checking for F/W updates... Using release information for Merlin Firmware. Required RAM: 111115 KB - RAM Free: 104452 KB - RAM Available: 180521 KB
> 
> Backup Started (by BACKUPMON) mount: mounting \192.168.1.250\nas on /tmp/mnt/astor failed: No route to host mount: mounting \192.168.1.250\nas on /tmp/mnt/astor failed: No route to host mount: mounting \192.168.1.250\nas on /tmp/mnt/astor failed: No route to host Backup Finished
> 
> Backup Failed
> 
> Sending email notification [NEW_BM_BACKUP_FAILED]. Please wait... The email notification was sent successfully [NEW_BM_BACKUP_FAILED].
> 
> **IMPORTANT NOTICE**: The firmware flash has been CANCELLED due to a failed backup from BACKUPMON. Please fix the BACKUPMON configuration, or consider uninstalling it to proceed flash. Resolving the BACKUPMON configuration is HIGHLY recommended for safety of the upgrade.
> 
> ## Press to return to the Main Menu...
> Latest release version is 3004.388.8.4.
> Downloading https://sourceforge.net/projects/asuswrt-merlin/files/RT-AX86U/Release/RT-AX86U_3004_388.8_4.zip
> .
> .
> .
> Required RAM: 111115 KB - RAM Free: 74968 KB - RAM Available: 178956 KB
> Archive: /tmp/mnt/asus/MerlinAU.d/RT-AX86U_firmware/RT-AX86U_firmware.zip Length Date Time Name
> 
> 84410388 11-17-2024 15:06 RT-AX86U_3004_388.8_4_pureubi.w 9717 11-17-2024 15:25 README-merlin.txt 105327 11-17-2024 15:06 Changelog-NG.txt 98 11-17-2024 15:06 sha256sum.sha256
> 
> ## 84525530 4 files
> ## Archive: /tmp/mnt/asus/MerlinAU.d/RT-AX86U_firmware/RT-AX86U_firmware.zip
> inflating: RT-AX86U_3004_388.8_4_pureubi.w
> inflating: Changelog-NG.txt
> inflating: sha256sum.sha256
> Required RAM: 111115 KB - RAM Free: 31056 KB - RAM Available: 157530 KB Current version NOT found in changelog file. Bypassing changelog verification for this run. Required RAM: 111115 KB - RAM Free: 31184 KB - RAM Available: 157870 KB No ROG Build detected. Skipping. SHA256 signature check for firmware image file passed successfully. Required RAM: 111115 KB - RAM Free: 30432 KB - RAM Available: 157413 KB Router Web URL is: http://RT-AX86U-M.?????? **IMPORTANT**: The firmware flash is about to start. Press to stop now, or type Y to continue. Once started, the flashing process CANNOT be interrupted. Continue? [yY|nN]? y
> 
> OK
> 
> Restarting web server... Please wait.
> 
> ## Sending email notification [START_FW_UPDATE_STATUS].
> Please wait...
> The email notification was sent successfully [START_FW_UPDATE_STATUS].
> % Total % Received % Xferd Average Speed Time Time Time Current
> Dload Upload Total Spent Left Speed
> 100 228 0 84 100 144 1834 3145 --:--:-- --:--:-- --:--:-- 5066
> Searching for Entware services to stop...
> Stopping Entware services...
> Please wait.
> ## /opt/etc/init.d/S61unbound
> /opt/etc/init.d/S15upsd
> /opt/etc/init.d/S15upsmon
> /opt/etc/init.d/S80lighttpd
> /opt/etc/init.d/S06tailscaled
> Checking lighttpd... alive. Shutting down lighttpd... done. Checking unbound... alive. Shutting down unbound... done. Checking upsmon... alive. Shutting down upsmon... done. Checking upsd... alive. Shutting down upsd... done. Checking tailscaled... alive. Shutting down tailscaled...`
> 
> ...and that's all the output I've had. However, the firmware upgrade, emails all worked. However, based on the warning above the script should have returned to the main menu based on the failed backup.

Great catch, I've already found my mistake and fixing it now. Please stand by.

**Comment by ExtremeFiretop** [comment]
@Martinski4GitHub 

For reference, this was broken in PR: https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/pull/275/files
There is no catch for if Backupmon fails anymore LOL.

Adjusting now.

**Comment by ExtremeFiretop** [comment]
@dorner365 

The fix is currently apart of PR: https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/pull/364

**Comment by ExtremeFiretop** [comment]
Hi @dorner365 

@Martinski4GitHub just merged the PR with the fix into dev. I'll close this issue completely once it goes to production :)

Thanks again for reporting!
